# Week 12 Homework - Generate fake data

Extend the class `FakeDataGenerator` and add the following features to the extended class.

* Email address
* Phone number
* Person's name
* Year born. (Use realistic values.)
* Number of kids. (Use realistic values.)
* Marital status. (Single/Married) 
* Annual income. (Optional challenge: Use a non-uniform distribution)

* have a method to write it to a file in csv format

In [1]:
# Use this or replace this with yours from your week10 hw. (It's up to you.)

import pandas as pd
import random
from faker import Faker

class FakeDataGenerator:
    
    def __init__(self, df = None, rows=5):
        """
        This class generates fake data
        
        If data frame is passed in it will add the fake data to it. 
        Otherwise, it will create a new data frame
        
        Parameters:
        -----------
        df: 
          DataFrame default is None
          
        rows:
          If df None, this parameter will be used to create a data frame with `row` length
        """
        # code goes under this line. 
        # I will deduct points if any code is written above the comments!
          
        self.fake = Faker()
        
        if df is not None:
            self.df = df
            self.rows = len(df)
        else:
            self.df = pd.DataFrame()
            self.rows = rows
        
        
    def add_random_number(self, column_name, small_value, high_value): # optional: add probabilities 
        """
        adds fake numbers to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        self.df[column_name] = [random.randint(small_value,high_value) for i in range(self.rows)]
        
        return self.df       
    
        
    def add_name(self, column_name):
        """
        adds fake name to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """

        self.df[column_name] = [self.fake.first_name() for i in range(self.rows)]
        
        return self.df
    
    
   
    
    def add_email(self, column_name):
        """
        adds fake email to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """

        self.df[column_name] = [self.fake.email() for i in range(self.rows)]
        
        return self.df
    
    
    def add_phone_number(self, column_name):
        """
        adds fake phone number to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        self.df[column_name] = [self.fake.phone_number() for i in range(self.rows)]
        
        return self.df
    
    
    def add_address(self, column_name):
        """
        adds fake address to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        self.df[column_name] = [self.fake.address() for i in range(self.rows)]
        
        return self.df

In [2]:
# complete this
class PocDataGenerator(FakeDataGenerator):
    def year_born(self, column_name):
        self.df[column_name] = [random.randint(1940,2021) for i in range(self.rows)]
        return self.df
    def no_of_kids(self, column_name):
        
        
        for i in range(self.rows):
            if self.df.iloc[:, 2][i] == 'single' :
                self.df.at[i,column_name] = 0
            else:
                self.df.at[i,column_name] = random.randint(1,10)
        self.df[column_name] = self.df[column_name].astype(int)
        

        return self.df
    def maritial_status(self, column_name):
        
        for i in range(self.rows):
            if self.df.iloc[:, 1][i] > 1991 :
                self.df.at[i,column_name] = 'single'
            else:
                self.df.at[i,column_name] = 'married'

        #self.df[column_name] = [random.choice(foo) for i in range(self.rows)]
        
        return self.df
    def annual_income(self, column_name):
        self.df[column_name] = [random.randint(10000,100000) for i in range(self.rows)]
        return self.df

In [3]:

g = PocDataGenerator()

In [4]:

g.add_address('home_address')
g.year_born('year_of_birth')
g.maritial_status('maritial_statuss')
g.no_of_kids('number_of_kids')
df = g.annual_income('annual_income')
df

,home_address,year_of_birth,maritial_statuss,number_of_kids,annual_income
0,"480 Lisa Rest\nWest Sydney, OH 07203",1973,married,3,64296
1,"9052 Thomas Greens Suite 388\nLake Denise, OR ...",1953,married,2,34703
2,"7103 Sarah Mount\nKristieview, MO 68107",1963,married,7,22879
3,"6744 Beth Ranch\nWest Kennethhaven, FL 46019",2006,single,0,72135
4,"891 Joel Park Apt. 051\nNorth Laurie, KS 51733",1985,married,7,94331

In [6]:
df.to_csv(r'C:\Users\Dell\Data - 601\assignment12.csv')